function loadergame()
    require("api.graphics")
    enet = require("enet")
    love.graphics.clear()
    love.graphics.setColor(1,1,1)
    love.graphics.rectangle("fill",0,0,10000,10000)
    love.graphics.setColor(0,0,0)
    gr.draw.txt("LOADING GAME",100,100,1,1)
    love.graphics.present()
    love.window.setIcon(love.image.newImageData("res/500icon.png"))
    require("api.player")
    require("api.langsys")
    require("api.savesys")
    require("api.item")
    require("api.inventory")
    require("api.obj")
    require("api.gui")
    require("api.multiplayer")
    require("api.guiloader")
    guiload.loadgui()
    require("api.sfx")
    love.audio.setVolume(0.25)
    camera = require("api.camera")
    --game camera
    cam = camera()
    --minimap
    mnm = camera()
    gr.texture.load()
    gr.texture.parse()
    sfx.loadsound()
    love.graphics.setColor(0,0,0)
    loading=false
end